### ISSUE TITLE
Pusher::trigger return false

### ISSUE THREAD

**Issue by phuongphally** [vinkla/laravel-pusher#22]
Pusher::trigger return false  
In laravel 5.4

**Comment by vinkla** [comment]
You need to provide **a lot more information** if you want our help. Just saying something doesn't work or returns a specific value wont get you anywhere.

**Comment by phuongphally** [comment]
I can not send message send to pusher console or client JavaScript. 
I can not see any errors .

I used $result =   Pusher::trigger('my-channel', 'my-event', ['message' => 'going']);

dd($result); 

output : false.

**Comment by vinkla** [comment]
Try asking in the [official Pusher PHP repository](https://github.com/pusher/pusher-http-php). This is just a Laravel bridge.

**Comment by rodrigosaavedra** [comment]
@phuongphally Did you manage to send the trigger? I have the same problem thanks

**Comment by jaap** [comment]
@phuongphally ans @rodrigosaavedra I hade the same issue. After turning on debug mode in config/pusher.php I found out I was getting a `false` because of an 'Unknown auth key'. Turns out I needed to set the cluster.

Adjusting your pusher.php config to somehting like this will probably resolve;

```
       'main' => [
            'auth_key' => ENV('PUSHER_APP_KEY'),
            'secret' => ENV('PUSHER_APP_SECRET'),
            'app_id' => ENV('PUSHER_APP_ID'),
            'options' => [
                'debug' => ENV('PUSHER_DEBUG_MODE'),
                'cluster' => 'eu' // Add this setting
            ],
            'host' => null,
            'port' => null,
            'timeout' => null,
        ],
```
Related issues/links:
#11 - Support for cluster name
Cluster setting: https://stackoverflow.com/questions/39132028/pusher-in-php-do-not-send-events-unknown-auth-key

**Comment by kamhawy4** [comment]
CLUSTER=eu

**Comment by fabioduque** [comment]
Actually for me the issue was having the option `encrypted` set to true (as in the example code from Pusher).

I've changed it to false, and it worked.

`'encrypted' => false`
